#!/bin/bash -xe

dotfiles_base="$(cd $(dirname "$0") && pwd)"
dotfiles_relative_from_home="${dotfiles_base/$HOME\/}"

# Git
git config --global include.path "$dotfiles_base/.gitconfig"
git config --global core.autocrlf input

# Install dotfiles
ln -snfv "$dotfiles_relative_from_home/.zshrc" "$HOME/.zshrc"
ln -snfv "$dotfiles_relative_from_home/.vimrc" "$HOME/.vimrc"
ln -snfv "$dotfiles_relative_from_home/.gvimrc" "$HOME/.gvimrc"

# Create dotvim
mkdir -p -v "$HOME/.vim"
mkdir -p -v "$HOME/.vim/tmp"
chmod 700 "$HOME/.vim" || true
