#!/bin/bash -xe

dotfiles_base="$(cd $(dirname "$0") && pwd)"
dotfiles_relative_from_home="${dotfiles_base/$HOME\/}"

# Do not set the Git user in Codespaces
if ! git config --get user.email; then
  git config --global user.name "$(cd "$dotfiles_base" && git log -1 --format=format:%an)"
  git config --global user.email "$(cd "$dotfiles_base" && git log -1 --format=format:%ae)"
fi

# Git
git config --global include.path "$dotfiles_base/.gitconfig"
git config --global core.autocrlf input

# Install dotfiles
ln -snfv "$dotfiles_relative_from_home/.zshrc" "$HOME/.zshrc"
ln -snfv "$dotfiles_relative_from_home/.vimrc" "$HOME/.vimrc"
ln -snfv "$dotfiles_relative_from_home/.gvimrc" "$HOME/.gvimrc"

# Create dotvim
mkdir -p -v "$HOME/.vim"
mkdir -p -v "$HOME/.vim/tmp"
chmod 700 "$HOME/.vim" || true
